title: Helion
views:
  - path: helion
    title: Helion
    icon: mdi:home-variant
    cards:
      - type: entities
        entities:
          - binary_sensor.updater
        title: Binary sensor
      - type: entities
        entities:
          - cover.the_gate
          - cover.garage
          - cover.blinds
      - type: entities
        entities:
          - lock.front_door_doorlock
      - type: entities
        entities:
          - person.kevin_jiao
        title: Person
      - type: entities
        entities:
          - sun.sun
        title: Sun
      - type: entities
        entities:
          - entity: binary_sensor.updater
          - entity: persistent_notification.http_login
          - entity: person.kevin_jiao
          - entity: sun.sun
          - entity: weather.home
          - entity: zone.home
        title: Entities
      - type: weather-forecast
        entity: weather.home
        show_forecast: false
      - type: entity
        entity: weather.home
        name: Entity (Home)
        attribute: temperature
        state_color: false

  - path: helion_output
    title: test
    icon: mdi:flash
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
